### ISSUE TITLE
Comments are not allowed to contain newlines

### ISSUE THREAD

**Issue by Lucaskyy** [valderman/4koma#1]
Comments are not allowed to contain newlines or carriage returns.
Try saving a file with these contents:
```toml
# This file contains the configuration for all items.
# It is highly recommended to edit this in-game.
```
then parsing it using this code:
```kt
TomlValue.from(itemConfigurationPath)
```
will result in this error:
```
cc.ekblad.toml.model.TomlException$ParseError: toml parse error, on line 1: disallowed character(s) encountered: 13
	at cc.ekblad.toml.serialization.TomlParserAdapterKt.throwOnBadChar(TomlParserAdapter.kt:181) ~[4koma-1.0.1.jar:?]
	at cc.ekblad.toml.serialization.TomlParserAdapterKt.extractExpression(TomlParserAdapter.kt:21) ~[4koma-1.0.1.jar:?]
	at cc.ekblad.toml.serialization.TomlParserAdapterKt.extractDocument(TomlParserAdapter.kt:15) ~[4koma-1.0.1.jar:?]
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(TomlDeserializer.kt:51) ~[4koma-1.0.1.jar:?]
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(TomlDeserializer.kt:36) ~[4koma-1.0.1.jar:?]
```
Note: I am on Windows 10.

**Comment by valderman** [comment]
Good catch! Will put out a 1.0.2 release with a fix in a moment.

**Comment by Lucaskyy** [comment]
Thank you!
